### PR TITLE
Update to Rust 2018 and update dependencies

### PR DESCRIPTION
**Pull request by fwalch**

### CODE REVIEW

**Comment by fwalch** [comment]
@mbr friendly ping :)

**Comment by endeav0r** [comment]
Is this project still being maintained?

**Comment by fwalch** [comment]
@endeav0r Maybe not (see also #11).

**Comment by marcelbuesing** [comment]
@mbr would you be willing to let others take over the maintenance of the crate ?

**Comment by mbr** [comment]
It's a bit stuck right now, since the next major release has functionality that is not working and that has been blocking fixes.

If someone is offering to maintain it without moving it, I'd be happy to consider that =)

**Pull request merged**
