### PR TITLE
Added CanBCMSocket.

### PR DESCRIPTION
**Pull request by marcelbuesing**
Implement support for SocketCAN's broadcastmanager.

### CODE REVIEW

**Comment by marcelbuesing** [comment]
@mbr I can also squash the commits. Let me know what you prefer.
What likely needs some efficiency improvement is how frames are read in `CanBCMSocket::read_frames`. Currently `MAX_NFRAMES` is read, which means 256*`CanFrame` is allocated for reading. I'm sure there is some way to only allocate nframes during reading but I can not figure it out. I tried reading n times from the buffer as you can see [here](https://github.com/marcelbuesing/socketcan-rs/blob/dev/src/lib.rs#L865), but the result is not what I expect (maybe due to alignment?).

**Comment by marcelbuesing** [comment]
Nevermind I missed the datagram part, so this is as efficient I guess as it can get.

**Comment by mbr** [comment]
Thanks for submitting this. I will need some time to review it, but I'll try to do that as soon as possible.

Thank you!

**Comment by mbr** [comment]
I've been working on this, but I am not 100% happy with the result yet, I'm sorry. This is not dead yet though!

**Comment by marcelbuesing** [comment]
Certainly, take your time. FYI I have sometimes had trouble with setting the filter using the `BcmMessageHead` struct. On some machines it worked with the vcan but not with can. The other way around on other machines as well (ARM/Intel). It turned out that  in C the `frames` array in the BcmMessageHead struct allocates 4bytes (although empty). This lead to adding the `_pad: u32,` to the end of the struct. Nevertheless this still leads to trouble with some cans where it previously worked without the additional 4 byte. Maybe you have an idea where this comes from.

**Pull request closed without merging**
